on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ".github/**"
      - "android/**"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  pull_request:
    branches:
      - master
name: Development
jobs:
  build:
    name: Build-Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore Keystore
        if: github.repository == 'timoknapp/sound-on-fire'
        run: |
          echo "${{ secrets.KEYSTORE }}" > sound-on-fire.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch sound-on-fire.jks.asc > android/sound-on-fire.jks

      - name: Update build number
        if: github.ref != 'refs/heads/master' && github.repository == 'timoknapp/sound-on-fire'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./.github/scripts/bumpVersion.sh
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add pubspec.yaml
          git commit -m "chore(version): bump build number"
          git push

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'

      - name: Build
        id: prepare-build
        run: |
          ./.github/scripts/buildAndroid.sh beta "${{ secrets.KEYSTORE_PASSWORD }}" "${{ secrets.KEY_PASSWORD }}" "${{ secrets.KEY_ALIAS }}" "${{ secrets.APP_CENTER_SECRET }}"
          echo "::set-output name=dir::$(cat tmp_artifact_path.txt)"
          echo "::set-output name=file::$(cat tmp_artifact_name.txt)"

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.prepare-build.outputs.file }}
          path: ${{ steps.prepare-build.outputs.dir }}
