on:
  workflow_dispatch:

name: Release

jobs:
  build:
    name: Semantic-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Go Semantic Release
      - name: Run Semantic Release
        uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: CHANGELOG.md
          dry: true # this will put the new version only in the '.version-unreleased' file.
          # update-file: .version

      - name: Set up Git
        if: steps.semrel.outputs.version != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Update pubspec.yaml
        if: steps.semrel.outputs.version != ''
        run: | # use '.version-unreleased' if in dry-mode
          echo "Version Release: ${{ steps.semrel.outputs.version }}"
          echo "Changelog: ${{ steps.semrel.outputs.changelog }}"
          echo "Version Unreleased: $(cat .version-unreleased)"
          echo "CHANGELOG.md: $(cat CHANGELOG.md)"
          ./.github/scripts/updateVersion.sh "$(cat .version-unreleased)"

      - name: Restore Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" > sound-on-fire.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch sound-on-fire.jks.asc > android/sound-on-fire.jks

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'dev' or 'beta'

      - name: Prepare & Build
        id: prepare-build
        run: |
          ./.github/scripts/buildAndroid.sh release "${{ secrets.KEYSTORE_PASSWORD }}" "${{ secrets.KEY_PASSWORD }}" "${{ secrets.KEY_ALIAS }}" "${{ secrets.APP_CENTER_SECRET }}"
          echo "::set-output name=dir::$(cat tmp_artifact_path.txt)"
          echo "::set-output name=file::$(cat tmp_artifact_name.txt)"

      - name: Update In-App Update Config
        id: update-config
        run: |
          ./.github/scripts/updateAppChangelog.sh ${{ steps.create_release.outputs.upload_url }}
          git add pubspec.yaml app-update-changelog.json CHANGELOG.md
          git commit -m "chore(version): update release output"
          git push

      - name: Push tag
        id: tag
        if: steps.semrel.outputs.version != ''
        run: |
          appVersionName=$(cat pubspec.yaml | grep "version: " | cut -d ' ' -f2 | cut -d '+' -f1)
          appVersionCode=$(cat pubspec.yaml | grep "version: " | cut -d ' ' -f2 | cut -d '+' -f2)
          echo "Version: $appVersionName"
          echo "Version-Code: $appVersionCode"
          TAG="v$appVersionName+$appVersionCode"
          echo "::set-output name=name::$TAG"
          git push origin :refs/tags/${TAG}
          git tag -fa ${TAG} -m "Release $TAG"
          git push origin ${TAG}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.name }}
          release_name: Release ${{ steps.tag.outputs.name }}
          draft: false
          prerelease: false
          body: ${{ steps.semrel.outputs.changelog }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ${{ steps.prepare-build.outputs.dir }}
          asset_name: ${{ steps.prepare-build.outputs.file }}
          asset_content_type: application/apk

      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: timo_knapp/SoundOnFire
          token: ${{secrets.APP_CENTER_API_TOKEN}}
          group: public
          file: ${{ steps.prepare-build.outputs.dir }}
