on:
  workflow_dispatch:

name: SoundOnFire-Semantic-Release

jobs:
  build:
    name: Semantic-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Go Semantic Release
      - name: Run Semantic Release
        uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: true
          update-file: .version
          # dry: true

      - name: Post Semantic Release Job
        run: |
          echo Version: ${{ steps.semrel.outputs.version.version }}
          echo Raw: ${{ steps.semrel.outputs.version.raw }}
          echo Major: ${{ steps.semrel.outputs.version.major }}
          echo Minor: ${{ steps.semrel.outputs.version.minor }}
          echo Patch: ${{ steps.semrel.outputs.version.patch }}
        if: steps.semrel.outputs.version != ''
      # - name: Post Semantic Release Job
      #   run: ./.github/scripts/updateVersion.sh ${{ steps.semrel.outputs.version }}
      #   if: steps.semrel.outputs.version != ''
      # - name: Update Release Version
      #   if: steps.semrel.outputs.version != ''
      #   uses: EndBug/add-and-commit@v4
      #   with:
      #     author_name: timoknapp
      #     author_email: mail@timoknapp.com
      #     message: "chore(version): update version"
      #     add: "pubspec.yaml"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
